import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/nav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return  (
         <html lang="en">
          <body className="mx-auto bg-[linear-gradient(to_right,#E6E6FA,#FFE1F2,#FDE8CD,#FFF7DA)]">
            <Navbar/>
        <main>{children}</main>
        </body>
         </html>        
  );
}
